version: '3.3'

volumes:
  backend_static:
  pg_data:
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - ../ref_system/.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - djangonetwork
  backend:
    build: ../ref_system/
    container_name: backend
    command: gunicorn --bind 0.0.0.0:8000 ref_system.wsgi
    env_file:
      - ../ref_system/.env
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - backend_static:/app/static/
    networks:
      - djangonetwork
  nginx:
    container_name: nginx_web
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/app/static/
    networks:
      - djangonetwork
networks:
    djangonetwork:
        driver: bridge