# Generated by Django 5.0.4 on 2024-04-20 16:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='номер телефона')),
                ('username', models.CharField(max_length=20, null=True, unique=True, verbose_name='Логин')),
                ('reg_data', models.DateField(auto_now_add=True, verbose_name='Зарегестрирован в системе')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
