# Generated by Django 5.0.4 on 2024-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customusermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
