# Generated by Django 5.0.4 on 2024-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customusermodel_user_referal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='invitation_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Реферальный идентификатор пригласившего пользователя'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='user_referal_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Реферальный идентификатор пользователя'),
        ),
    ]
